package com.carlos.ismartshell.ui.theme
import androidx.compose.ui.graphics.Color

// ─────────────────────────────────────────────────────────────────────────────
// LIGHT SCHEME
// primary    = Naranja  #F97316
// secondary  = Purple   #8B5CF6
// tertiary   = Navy     #1E1B4B
// background = Warm white #FFF9EE
// ─────────────────────────────────────────────────────────────────────────────

val primaryLight                = Color(0xFFF97316)
val onPrimaryLight              = Color(0xFFFFFFFF)
val primaryContainerLight       = Color(0xFFFFDEBF)
val onPrimaryContainerLight     = Color(0xFF4A1800)

val secondaryLight              = Color(0xFF8B5CF6)
val onSecondaryLight            = Color(0xFFFFFFFF)
val secondaryContainerLight     = Color(0xFFEDE9FE)
val onSecondaryContainerLight   = Color(0xFF2E0D6E)

val tertiaryLight               = Color(0xFF1E1B4B)
val onTertiaryLight             = Color(0xFFFFFFFF)
val tertiaryContainerLight      = Color(0xFFD4D0FF)
val onTertiaryContainerLight    = Color(0xFF08062A)

val errorLight                  = Color(0xFFBA1A1A)
val onErrorLight                = Color(0xFFFFFFFF)
val errorContainerLight         = Color(0xFFFFDAD6)
val onErrorContainerLight       = Color(0xFF93000A)

val backgroundLight             = Color(0xFFFFF9EE)
val onBackgroundLight           = Color(0xFF1E1B13)
val surfaceLight                = Color(0xFFFFF9EE)
val onSurfaceLight              = Color(0xFF1E1B13)
val surfaceVariantLight         = Color(0xFFFFEDD9)
val onSurfaceVariantLight       = Color(0xFF4B3728)
val outlineLight                = Color(0xFF7C6757)
val outlineVariantLight         = Color(0xFFCDBAAA)
val scrimLight                  = Color(0xFF000000)
val inverseSurfaceLight         = Color(0xFF332E27)
val inverseOnSurfaceLight       = Color(0xFFF7F0E2)
val inversePrimaryLight         = Color(0xFFFFB68A)
val surfaceDimLight             = Color(0xFFE6D9CC)
val surfaceBrightLight          = Color(0xFFFFF9EE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight    = Color(0xFFFFF3E8)
val surfaceContainerLight       = Color(0xFFF5EDDF)
val surfaceContainerHighLight   = Color(0xFFEDE5D7)
val surfaceContainerHighestLight= Color(0xFFE5DDD0)

// Medium contrast light
val primaryLightMediumContrast                  = Color(0xFFBF4F00)
val onPrimaryLightMediumContrast                = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast         = Color(0xFFFF8534)
val onPrimaryContainerLightMediumContrast       = Color(0xFFFFFFFF)
val secondaryLightMediumContrast                = Color(0xFF5B32C4)
val onSecondaryLightMediumContrast              = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast       = Color(0xFF9B76FF)
val onSecondaryContainerLightMediumContrast     = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast                 = Color(0xFF1E1B4B)
val onTertiaryLightMediumContrast               = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast        = Color(0xFF4E4A8A)
val onTertiaryContainerLightMediumContrast      = Color(0xFFFFFFFF)
val errorLightMediumContrast                    = Color(0xFF740006)
val onErrorLightMediumContrast                  = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast           = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast         = Color(0xFFFFFFFF)
val backgroundLightMediumContrast               = Color(0xFFFFF9EE)
val onBackgroundLightMediumContrast             = Color(0xFF1E1B13)
val surfaceLightMediumContrast                  = Color(0xFFFFF9EE)
val onSurfaceLightMediumContrast                = Color(0xFF131109)
val surfaceVariantLightMediumContrast           = Color(0xFFFFEDD9)
val onSurfaceVariantLightMediumContrast         = Color(0xFF3A2D20)
val outlineLightMediumContrast                  = Color(0xFF574234)
val outlineVariantLightMediumContrast           = Color(0xFF72574A)
val scrimLightMediumContrast                    = Color(0xFF000000)
val inverseSurfaceLightMediumContrast           = Color(0xFF332E27)
val inverseOnSurfaceLightMediumContrast         = Color(0xFFF7F0E2)
val inversePrimaryLightMediumContrast           = Color(0xFFFFB68A)
val surfaceDimLightMediumContrast               = Color(0xFFCCC0B4)
val surfaceBrightLightMediumContrast            = Color(0xFFFFF9EE)
val surfaceContainerLowestLightMediumContrast   = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast      = Color(0xFFFFF3E8)
val surfaceContainerLightMediumContrast         = Color(0xFFEDE5D7)
val surfaceContainerHighLightMediumContrast     = Color(0xFFE3DACB)
val surfaceContainerHighestLightMediumContrast  = Color(0xFFD7CEBD)

// High contrast light
val primaryLightHighContrast                    = Color(0xFF4A1800)
val onPrimaryLightHighContrast                  = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast           = Color(0xFFBF4F00)
val onPrimaryContainerLightHighContrast         = Color(0xFFFFFFFF)
val secondaryLightHighContrast                  = Color(0xFF2A0080)
val onSecondaryLightHighContrast                = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast         = Color(0xFF5B32C4)
val onSecondaryContainerLightHighContrast       = Color(0xFFFFFFFF)
val tertiaryLightHighContrast                   = Color(0xFF08062A)
val onTertiaryLightHighContrast                 = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast          = Color(0xFF1E1B4B)
val onTertiaryContainerLightHighContrast        = Color(0xFFFFFFFF)
val errorLightHighContrast                      = Color(0xFF600004)
val onErrorLightHighContrast                    = Color(0xFFFFFFFF)
val errorContainerLightHighContrast             = Color(0xFF98000A)
val onErrorContainerLightHighContrast           = Color(0xFFFFFFFF)
val backgroundLightHighContrast                 = Color(0xFFFFF9EE)
val onBackgroundLightHighContrast               = Color(0xFF1E1B13)
val surfaceLightHighContrast                    = Color(0xFFFFF9EE)
val onSurfaceLightHighContrast                  = Color(0xFF000000)
val surfaceVariantLightHighContrast             = Color(0xFFFFEDD9)
val onSurfaceVariantLightHighContrast           = Color(0xFF000000)
val outlineLightHighContrast                    = Color(0xFF2F2218)
val outlineVariantLightHighContrast             = Color(0xFF4D3B2D)
val scrimLightHighContrast                      = Color(0xFF000000)
val inverseSurfaceLightHighContrast             = Color(0xFF332E27)
val inverseOnSurfaceLightHighContrast           = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast             = Color(0xFFFFB68A)
val surfaceDimLightHighContrast                 = Color(0xFFBEB3A7)
val surfaceBrightLightHighContrast              = Color(0xFFFFF9EE)
val surfaceContainerLowestLightHighContrast     = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast        = Color(0xFFF7F0E2)
val surfaceContainerLightHighContrast           = Color(0xFFE5DDD0)
val surfaceContainerHighLightHighContrast       = Color(0xFFD9D0C2)
val surfaceContainerHighestLightHighContrast    = Color(0xFFCCC4B5)

// ─────────────────────────────────────────────────────────────────────────────
// DARK SCHEME
// ─────────────────────────────────────────────────────────────────────────────

val primaryDark                 = Color(0xFFFFB68A)
val onPrimaryDark               = Color(0xFF4A1800)
val primaryContainerDark        = Color(0xFFBF4F00)
val onPrimaryContainerDark      = Color(0xFFFFDEBF)

val secondaryDark               = Color(0xFFCBB2FF)
val onSecondaryDark             = Color(0xFF2E0D6E)
val secondaryContainerDark      = Color(0xFF5B32C4)
val onSecondaryContainerDark    = Color(0xFFEDE9FE)

val tertiaryDark                = Color(0xFFBEB8FF)
val onTertiaryDark              = Color(0xFF1E1B4B)
val tertiaryContainerDark       = Color(0xFF2C2870)
val onTertiaryContainerDark     = Color(0xFFD4D0FF)

val errorDark                   = Color(0xFFFFB4AB)
val onErrorDark                 = Color(0xFF690005)
val errorContainerDark          = Color(0xFF93000A)
val onErrorContainerDark        = Color(0xFFFFDAD6)

val backgroundDark              = Color(0xFF15130B)
val onBackgroundDark            = Color(0xFFE8E2D4)
val surfaceDark                 = Color(0xFF15130B)
val onSurfaceDark               = Color(0xFFE8E2D4)
val surfaceVariantDark          = Color(0xFF4B3728)
val onSurfaceVariantDark        = Color(0xFFCDBAA8)
val outlineDark                 = Color(0xFF9A8878)
val outlineVariantDark          = Color(0xFF4B3728)
val scrimDark                   = Color(0xFF000000)
val inverseSurfaceDark          = Color(0xFFE8E2D4)
val inverseOnSurfaceDark        = Color(0xFF332E27)
val inversePrimaryDark          = Color(0xFFF97316)
val surfaceDimDark              = Color(0xFF15130B)
val surfaceBrightDark           = Color(0xFF3C3830)
val surfaceContainerLowestDark  = Color(0xFF100E07)
val surfaceContainerLowDark     = Color(0xFF1E1B13)
val surfaceContainerDark        = Color(0xFF221F17)
val surfaceContainerHighDark    = Color(0xFF2D2A21)
val surfaceContainerHighestDark = Color(0xFF38342B)

// Medium contrast dark
val primaryDarkMediumContrast                   = Color(0xFFFFCA9E)
val onPrimaryDarkMediumContrast                 = Color(0xFF2E0C00)
val primaryContainerDarkMediumContrast          = Color(0xFFD46410)
val onPrimaryContainerDarkMediumContrast        = Color(0xFF000000)
val secondaryDarkMediumContrast                 = Color(0xFFDDCAFF)
val onSecondaryDarkMediumContrast               = Color(0xFF1E006A)
val secondaryContainerDarkMediumContrast        = Color(0xFF9B76FF)
val onSecondaryContainerDarkMediumContrast      = Color(0xFF000000)
val tertiaryDarkMediumContrast                  = Color(0xFFD4D0FF)
val onTertiaryDarkMediumContrast                = Color(0xFF080527)
val tertiaryContainerDarkMediumContrast         = Color(0xFF7774C0)
val onTertiaryContainerDarkMediumContrast       = Color(0xFF000000)
val errorDarkMediumContrast                     = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast                   = Color(0xFF540003)
val errorContainerDarkMediumContrast            = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast          = Color(0xFF000000)
val backgroundDarkMediumContrast                = Color(0xFF15130B)
val onBackgroundDarkMediumContrast              = Color(0xFFE8E2D4)
val surfaceDarkMediumContrast                   = Color(0xFF15130B)
val onSurfaceDarkMediumContrast                 = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast            = Color(0xFF4B3728)
val onSurfaceVariantDarkMediumContrast          = Color(0xFFE3CFBB)
val outlineDarkMediumContrast                   = Color(0xFFB8A898)
val outlineVariantDarkMediumContrast            = Color(0xFF9A8878)
val scrimDarkMediumContrast                     = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast            = Color(0xFFE8E2D4)
val inverseOnSurfaceDarkMediumContrast          = Color(0xFF2D2A21)
val inversePrimaryDarkMediumContrast            = Color(0xFFBF4F00)
val surfaceDimDarkMediumContrast                = Color(0xFF15130B)
val surfaceBrightDarkMediumContrast             = Color(0xFF484239)
val surfaceContainerLowestDarkMediumContrast    = Color(0xFF090703)
val surfaceContainerLowDarkMediumContrast       = Color(0xFF201D15)
val surfaceContainerDarkMediumContrast          = Color(0xFF2A271F)
val surfaceContainerHighDarkMediumContrast      = Color(0xFF353229)
val surfaceContainerHighestDarkMediumContrast   = Color(0xFF413D34)

// High contrast dark
val primaryDarkHighContrast                     = Color(0xFFFFECDC)
val onPrimaryDarkHighContrast                   = Color(0xFF000000)
val primaryContainerDarkHighContrast            = Color(0xFFFFB68A)
val onPrimaryContainerDarkHighContrast          = Color(0xFF1A0500)
val secondaryDarkHighContrast                   = Color(0xFFF3ECFF)
val onSecondaryDarkHighContrast                 = Color(0xFF000000)
val secondaryContainerDarkHighContrast          = Color(0xFFCBB2FF)
val onSecondaryContainerDarkHighContrast        = Color(0xFF0D0035)
val tertiaryDarkHighContrast                    = Color(0xFFECEBFF)
val onTertiaryDarkHighContrast                  = Color(0xFF000000)
val tertiaryContainerDarkHighContrast           = Color(0xFFBEB8FF)
val onTertiaryContainerDarkHighContrast         = Color(0xFF020018)
val errorDarkHighContrast                       = Color(0xFFFFECE9)
val onErrorDarkHighContrast                     = Color(0xFF000000)
val errorContainerDarkHighContrast              = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast            = Color(0xFF220001)
val backgroundDarkHighContrast                  = Color(0xFF15130B)
val onBackgroundDarkHighContrast                = Color(0xFFE8E2D4)
val surfaceDarkHighContrast                     = Color(0xFF15130B)
val onSurfaceDarkHighContrast                   = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast              = Color(0xFF4B3728)
val onSurfaceVariantDarkHighContrast            = Color(0xFFFFFFFF)
val outlineDarkHighContrast                     = Color(0xFFF7ECDF)
val outlineVariantDarkHighContrast              = Color(0xFFC9B8A8)
val scrimDarkHighContrast                       = Color(0xFF000000)
val inverseSurfaceDarkHighContrast              = Color(0xFFE8E2D4)
val inverseOnSurfaceDarkHighContrast            = Color(0xFF000000)
val inversePrimaryDarkHighContrast              = Color(0xFFBF4F00)
val surfaceDimDarkHighContrast                  = Color(0xFF15130B)
val surfaceBrightDarkHighContrast               = Color(0xFF534E45)
val surfaceContainerLowestDarkHighContrast      = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast         = Color(0xFF221F17)
val surfaceContainerDarkHighContrast            = Color(0xFF332E27)
val surfaceContainerHighDarkHighContrast        = Color(0xFF3E3A31)
val surfaceContainerHighestDarkHighContrast     = Color(0xFF4A463D)